### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by Koceto1973** [danbev/learning-libuv#1]
Hi,
following steps from your README.md,
on
cmake -DCMAKE_BUILD_TYPE=Debug
I got the following error:
The source directory ".../projects/libuv/build" does not appear to contain CMakeLists.txt.

Shall I copy the file from parent dir and retry same command in build dir?

**Comment by danbev** [comment]
Sorry about the confusion here. I've updated the instruction as it was missing the directory (`..`) in it.

**Comment by Koceto1973** [comment]
Thanks a lot, this went well!

Later on, 'make test' failed on both tests - Ubuntu 18.04.4 LTS here.

**Comment by danbev** [comment]
> Later on, 'make test' failed on both tests - Ubuntu 18.04.4 LTS here.

I'm pretty sure these are test in libuv, but I also noticed that there is mention of running the test in the readme which I've now removed and replaced with some instructions about building the executables in this project.

**Comment by Koceto1973** [comment]
Yes, I tried 'make test' as per your instructions in README.md .
Might be I misinterpret something - only the .gitignore file and README.md have recent updates,
and I can't find check.c in the repo tree, 'make check'  from .../libuv or .../libuv/build returns 
make: *** No rule to make target 'check'.  Stop.

**Comment by danbev** [comment]
So this project is just a collection notes and code samples related to libuv. I've included the build instructions for libuv just so I have them somewhere and include debug symbols. 

After libuv is built then the rest of the code exist in in this project. For example, [check.c](https://github.com/danbev/learning-libuv/blob/master/check.c) and other c source code contains small isolate code examples that try to show usages of libuv in isolation that I can use as a reference.

Does that makes sense?

**Comment by Koceto1973** [comment]
Sure It does, thanks a lot!
Do you use some other board to reference and discuss the samples code?
Lots of questions come to mind while getting familiar with the library :)
